sudo: required
services:
  - docker

os: linux
dist: xenial
language: minimal

before_install:
  - echo 'Loading repository configs'
  - . ./.ci/repos.conf
  - echo 'Detecting changes to tool files...'
  - git diff --quiet "$TRAVIS_COMMIT_RANGE" --; GIT_DIFF_EXIT_CODE=$?
  - |
    if [ "$GIT_DIFF_EXIT_CODE" -gt 1 ]; then
        git remote set-branches --add origin master
        git fetch
        TRAVIS_COMMIT_RANGE=origin/master...
    fi
  - echo "\$TRAVIS_COMMIT_RANGE is $TRAVIS_COMMIT_RANGE"
  - echo "Change detection limited to toolset directories:"; for d in "${!TOOLSET_REPOS[@]}"; do echo "${d}/"; done
  - |
    TOOLSET= ;
    while read op path; do
        if [ -n "$TOOLSET" -a "$TOOLSET" != "${path%%/*}" ]; then
            echo "ERROR: Changes to tools in multiple toolsets found, terminating: ${TOOLSET} != ${path%%/*}"
            travis_terminate 1
        elif [ -z "$TOOLSET" ]; then
            TOOLSET="${path%%/*}"
        fi
        case "${path##*.}" in
            lock)
                ;;
            *)
                continue
                ;;
        esac
        case "$op" in
            A|M)
                echo "$op $path"
                TOOL_YAMLS+=("${path}")
                ;;
        esac
    done < <(git diff --color=never --name-status "$TRAVIS_COMMIT_RANGE" -- $(for d in "${!TOOLSET_REPOS[@]}"; do echo "${d}/"; done))
  - set | grep '^TOOL'
  - |
    if [ ${#TOOL_YAMLS[@]} -eq 0 ]; then
        echo 'No tool changes, terminating'
        travis_terminate 0
    fi
  - REPO="${TOOLSET_REPOS[$TOOLSET]}"
  - |
    if [ -n "$REPO" ]; then
        echo "Setting up CVMFS for repo ${REPO}"
    else
        echo "ERROR: No repo defined for toolset $TOOLSET, set one in \$TOOLSET_REPOS"
        travis_terminate 1
    fi

install:
  - sudo pip install git+https://github.com/natefoo/ephemeris.git@spinner planemo
  - >-
    docker run -d -p 8080:80 --name=galaxy
    -e GALAXY_CONFIG_INSTALL_DATABASE_CONNECTION=sqlite:///${INSTALL_DATABASES[$REPO]}
    -e GALAXY_CONFIG_TOOL_CONFIG_FILE=${SHED_TOOL_CONFIGS[$REPO]}
    -e GALAXY_CONFIG_MASTER_API_KEY=deadbeef
    -e GALAXY_CONFIG_CONDA_PREFIX=${CONDA_PATHS[$REPO]}
    -e GALAXY_HANDLER_NUMPROCS=0
    -e CONDARC=${CONDA_PATHS[$REPO]}rc
    -v $(pwd)/.ci/job_conf.xml:/job_conf.xml
    -v $(pwd)/.ci/nginx.conf:/etc/nginx/nginx.conf
    -e GALAXY_CONFIG_JOB_CONFIG_FILE=/job_conf.xml
    bgruening/galaxy-stable
  - |
    galaxy-wait -v --timeout 120 || {
        echo "#### TIMED OUT WAITING FOR GALAXY ####";
        for f in /var/log/nginx/error.log /home/galaxy/logs/uwsgi.log; do
            echo "#### CONTENTS OF ${f}:";
            docker exec galaxy cat $f;
        done;
        echo "#### RESPONSE FROM http://localhost:8080:";
        curl http://localhost:8080;
        echo "#### TERMINATING BUILD";
        travis_terminate 1;
    }

script:
  - |
    for tool_yaml in "${TOOL_YAMLS[@]}"; do
        shed-tools install -v -a deadbeef -t "$tool_yaml" || {
            echo "#### TOOL INSTALL ERROR ####";
            for f in /var/log/nginx/error.log /var/log/nginx/access.log /home/galaxy/logs/uwsgi.log; do
                echo "#### TAIL OF ${f}:";
                docker exec galaxy tail -500 $f;
            done;
            echo "#### TERMINATING BUILD";
            travis_terminate 1;
        }
    done

